default:
    tags:
      - k8s-aws-tools
    interruptible: true

stages:
  - build
  - deploy
  - release

variables:
  MKDOCS_IMAGE_VERSION: "0.3.8"
  MKDOCS_IMAGE_URL: "registry.gitlab.com/kxdev/documentation/framework/mkdocs-build"
  KUBERNETES_MEMORY_REQUEST: "512Mi"
  KUBERNETES_MEMORY_LIMIT: "1024Mi"
  BACKUP_DIR: "/tmp/backup"
  DRAFT_DIR: "/tmp/draft"
  LIVE_DIR: "/tmp/live"
  
build-job:
  image: "$MKDOCS_IMAGE_URL:$MKDOCS_IMAGE_VERSION"
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: always
  allow_failure: false
  before_script:
    - apt-get install -y zip wget
  script:
    - echo "######## build-job"
    - ./local.sh build
  artifacts:
    name: "local"
    paths:
      - local.zip
    expire_in: 2 days

.setup-ssh:
  image:
    name: "$MKDOCS_IMAGE_URL:$MKDOCS_IMAGE_VERSION"
    entrypoint: [""]
  before_script:
    - |
      # Write key into container
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      echo $CODEKXCOM_CI_KEY | base64 -d > ~/.ssh/id_rsa
      chmod 400 ~/.ssh/id_rsa
      eval $(ssh-agent)
      ssh-add ~/.ssh/id_rsa
      ssh-keyscan -t rsa -H code.kx.com >> ~/.ssh/known_hosts
      chmod 644 ~/.ssh/known_hosts

deploy-draft-job:
  stage: deploy
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  dependencies:
    - build-job
  when: on_success
  extends: .setup-ssh
  variables:
    DISPLAY: "1"
    CI_DEBUG_TRACE: "false"
    GIT_STRATEGY: none
    UNZIP_DIR: "/tmp/unzip"
  script:
    - echo "######## Available files in runner"
    - ls -al
    - |
      ssh ci@code.kx.com << EOF
        echo "######## Removing dir used to unzip i.e. ${UNZIP_DIR}"
        rm -rf ${UNZIP_DIR}
        mkdir -p ${UNZIP_DIR}
      EOF
    - scp local.zip ci@code.kx.com:${UNZIP_DIR}/
    - |
      ssh ci@code.kx.com << EOF
        echo "######## Unzip new site to ${UNZIP_DIR}/local"
        cd ${UNZIP_DIR}
        unzip local.zip 
        echo "######## Backing up ${DRAFT_DIR}/q (previous draft site) to ${BACKUP_DIR}/q_draft.bak"
        if [ ! -d ${DRAFT_DIR} ]; then mkdir -p ${DRAFT_DIR}; fi
        if [ ! -d ${BACKUP_DIR} ]; then mkdir -p ${BACKUP_DIR}; fi
        cd ${DRAFT_DIR}
        ls -l
        if [ -d q ]; then mv q ${BACKUP_DIR}/q_draft.bak;rm -rf q;echo "######## Old backed up to ${BACKUP_DIR}/q_draft.bak"; fi
        echo "######## Contents of backup dir ${BACKUP_DIR}"
        cd ${BACKUP_DIR}
        ls -l
        echo "######## Moving new site from ${UNZIP_DIR}/local to ${DRAFT_DIR}/q"
        mv ${UNZIP_DIR}/local ${DRAFT_DIR}/q
        echo "######## Contents of draft dir ${DRAFT_DIR}"
        cd ${DRAFT_DIR}
        pwd
        ls -l
        echo "######## Contents of draft q dir ${DRAFT_DIR}/q"
        cd ${DRAFT_DIR}/q
        pwd
        ls -l
      EOF

release_job:
  image: "$MKDOCS_IMAGE_URL:$MKDOCS_IMAGE_VERSION"
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  extends: .setup-ssh
  script:
    - echo "######## release_job"

