default:
    tags:
      - k8s-aws-tools
    interruptible: true

stages:
  - build
  - deploy

variables:
  MKDOCS_IMAGE_VERSION: "0.3.8"
  MKDOCS_IMAGE_URL: "registry.gitlab.com/kxdev/documentation/framework/mkdocs-build"
  KUBERNETES_MEMORY_REQUEST: "512Mi"
  KUBERNETES_MEMORY_LIMIT: "1024Mi"
  
build-job:
  image: "$MKDOCS_IMAGE_URL:$MKDOCS_IMAGE_VERSION"
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: always
  allow_failure: false
  before_script:
    - apt-get install -y zip wget
  script:
    - echo "build-job"
    - ./local.sh build
  artifacts:
    name: "local"
    paths:
      - local.zip
    expire_in: 2 days

deploy-job:
  image: "$MKDOCS_IMAGE_URL:$MKDOCS_IMAGE_VERSION"
  stage: deploy
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  dependencies:
    - build-job
  when: on_success
  script:
    - echo "deploy-job"
    - ls -al
  variables:
    GIT_STRATEGY: none
