default:
    tags:
      - k8s-aws-tools
    interruptible: true

build-job:
  stage: build
  variables:
    CI_DEBUG_TRACE: "true"  
  image: "registry.gitlab.com/kxdev/documentation/framework/mkdocs-build:0.3.8"
  script:
    - echo "foo"
    - ls -al
    - mkdocs -V
